"""Coder Agent — proposes whole-file rewrites for a task.

No diff generation: the agent returns full file contents, not a patch.
See the Phase 3 plan for why — LLM-generated unified diffs have a
documented failure mode (correct content, wrong hunk-header line numbers;
context drift across turns) that whole-file rewrite sidesteps entirely.
A diff for the human-readable approval preview is computed locally with
difflib elsewhere, never generated by the model.

No context-window budgeting on the world-model summary — fine at
personal-repo scale, would need truncation/summarization for large repos.
Not solved this phase.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable
from dataclasses import dataclass

from idemra.world_model.build import WorldModelResult

_FENCE_RE = re.compile(r"^```(?:json)?\s*\n?|\n?```$", re.MULTILINE)

PROMPT_TEMPLATE = """\
You are a coding agent. Given a task and a summary of a repository, propose
the full new contents of every file that needs to change to complete the
task. Do not propose a diff or patch — always return the COMPLETE new
content of each file you touch.

Task: {task}

Repository files:
{file_list}

Known symbols (functions/classes/imports):
{symbol_list}

Respond with ONLY a JSON array, no other text, in this exact shape:
[{{"path": "relative/path.py", "content": "full new file content"}}]
"""


class MalformedProposal(Exception):
    def __init__(self, message: str, raw_response: str) -> None:
        super().__init__(message)
        self.raw_response = raw_response


@dataclass(frozen=True)
class ProposedFile:
    path: str
    content: str


def _build_prompt(task: str, world_model: WorldModelResult) -> str:
    file_list = "\n".join(f"- {f.path} ({f.language or 'unknown'})" for f in world_model.snapshot.files)
    symbol_list = "\n".join(f"- {s.kind} {s.name} in {s.path}:{s.line}" for s in world_model.symbols)
    return PROMPT_TEMPLATE.format(task=task, file_list=file_list or "(none)", symbol_list=symbol_list or "(none)")


def _parse_response(raw: str) -> list[ProposedFile]:
    stripped = _FENCE_RE.sub("", raw.strip()).strip()
    try:
        parsed = json.loads(stripped)
    except json.JSONDecodeError as exc:
        raise MalformedProposal(f"response is not valid JSON: {exc}", raw) from exc

    if not isinstance(parsed, list):
        raise MalformedProposal(f"expected a JSON array, got {type(parsed).__name__}", raw)

    files = []
    for entry in parsed:
        if not isinstance(entry, dict) or "path" not in entry or "content" not in entry:
            raise MalformedProposal(f"malformed entry, expected {{path, content}}: {entry!r}", raw)
        files.append(ProposedFile(path=entry["path"], content=entry["content"]))
    return files


def propose_changes(
    task: str,
    world_model: WorldModelResult,
    complete: Callable[[str], str],
) -> list[ProposedFile]:
    prompt = _build_prompt(task, world_model)
    raw = complete(prompt)
    return _parse_response(raw)
