"""add source_ref to runs

Revision ID: 323871d19e38
Revises: 3537c04d8211
Create Date: 2026-08-19 01:00:41.938106

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '323871d19e38'
down_revision: str | Sequence[str] | None = '3537c04d8211'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('source_ref', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'source_ref')
    # ### end Alembic commands ###
